const localBasket = localStorage.getItem("basket");
const localFavorite = localStorage.getItem("favorite");
const localLang = localStorage.getItem("lang");
const initialState = {
    products: [

    ],
    categories: [

    ],
    subcategories: [

    ],
    t: {
        en: {
            home: "Home",
            shop: "Shop",
            about: "About",
            faqs: "Faqs",
            contact: "Contact",
            learnMore: "Learn More",
            shopNow: "Shop Now",
            forWoman: "For Woman",
            forMan: "For Man",
            bagShop: "Bag Shop",
            forKid: "For Kid",
            shoesShop: "Shoes Shop",
            all: "All",
            popular: "Popular",
            brand: "Brand",
            sale: "Sale",
            instagramGallery: "Instagram Gallery",
            searchProducts: "Search Products",
            categories: "Categories",
            kid: "Kid",
            woman: "Woman",
            men: "Men",
            shoes: "Shoes",
            bag: "Bag",
            color: "Color",
            filterByPrice: "Filter By Price",
            size: "Size",
            showing: "Showing",
            results: "Results",
            fromCheapToExpensive: "From Cheap To Expensive",
            fromExpensiveToCheap: "From Expensive To Cheap",
            a_z: "A - Z",
            z_a: "Z - A",
            availability: "Availability",
            price: "Price",
            inStock: "In Stock",
            notStock: "Not Stock",
            subcategory: "Subcategory",
            category: "Category",
            aboutTitle: "Everything is one click away: easy, fast and safe shopping!",
            aboutDesc: "Our shopping store is in front of you with a modern and fun platform for our customers to make comfortable and quality purchases. We have many different categories to choose from. Our shopping store is the best alternative for your shopping experience. By coming to us, you will always stay with us for quality products, best services and cheapest prices. We believe that we can provide you with a profitable and reliable shopping experience. We always take the wishes of our customers as the basis and protect their information.",
            freeShipping: "Free Shipping",
            freeShippingDesc: "ALL ORDER OVER 10 AZN",
            supportCustomer: "Support Customer",
            supportCustomerDesc: "SUPPORT 24/7",
            securePayments: "Secure Payments",
            securePaymentsDesc: "Safety protection",
            testimonial1: "I recently bought a pair of shoes from this store. I was impressed with the speedy service. The shoes are comfortable and of good quality. I will definitely shop here again!",
            testimonial2: "The store has a great selection of products and I was able to find exactly what I was looking for. The prices were reasonable and the customer service was excellent. I recommend this store to anyone looking for a great shopping experience.",
            testimonial3: "I have been a regular customer of this store for a long time and I am always impressed by the variety and quality of products. The staff are always friendly and helpful and I appreciate their service to ensure the best shopping experience possible.",
            testimonial4: "I needed a new dress for a special day and I was so happy to find it at this store. I was able to find the perfect material at a low price. I will definitely be back shopping again soon!",
            sendUsMesssage: "Send Us a Message",
            name: "Name",
            email: "Email",
            surname: "Surname",
            phone: "Phone",
            submit: "Submit",
            message: "Message",
            address: "Address",
            total: "Total",
            goBasket: "Go Basket",
            productName: "Product Name",
            quantity: "Quantity",
            favorites: "Favorites",
            instagram: "Instagram",
            facebook: "Facebook",
            twitter:"Twitter",
            azn:"AZN"
        },
        az: {
            home: "Ana Səhifə",
            shop: "Mağaza",
            about: "Haqqımızda",
            faqs: "Sual - Cavab",
            contact: "Əlaqə",
            learnMore: "Ətraflı Məlumat",
            shopNow: "Alışverişə başla",
            forWoman: "Qadınlar üçün",
            forMan: "Kişilər üçün",
            bagShop: "Çantalar",
            forKid: "Uşaqlar üçün",
            shoesShop: "Ayaqqabılar",
            all: "Hamısı",
            popular: "Ən çox satılanlar",
            brand: "Brend",
            sale: "Endirim",
            instagramGallery: "İnstagram Qalereya",
            searchProducts: "Məhsul axtarışı",
            categories: "Kateqoriya",
            kid: "Uşaqlar üçün ",
            woman: "Qadınlar üçün ",
            men: "Kişilər üçün ",
            shoes: "Ayaqqabılar",
            bag: "Çantalar",
            color: "Rəng",
            filterByPrice: "Qiymətə görə filterləmə",
            size: "Ölçü",
            showing: "Göstərilir :",
            results: "Nəticə",
            fromCheapToExpensive: "Ucuzdan Bahaya",
            fromExpensiveToCheap: "Bahadan Ucuza",
            a_z: "A - Z",
            z_a: "Z - A",
            availability: "Mövcudluq",
            price: "Qiymət",
            inStock: "Mövcuddur",
            notStock: "Mövcud deyil",
            subcategory: "Altkateqoriya",
            category: "Kateqoriya",
            aboutTitle: "Hər şey tek bir klik uzağınızda: asan, sürətli və təhlükəsiz alışveriş!",
            aboutDesc: "Alış veriş mağazamız, müştərilərimizin rahat və keyfiyyətli alış veriş etməkləri üçün müasir və əyləncəli bir platforma ilə qarşınızdadır. Biz birçox fərqli kateqoriyalardan ibarət seçimlərə sahibik.Bizim alış veriş mağazamız sizin alış veriş təcrübəniz üçün ən yaxşı alternativdir. Bizə gələrək, siz daima keyfiyyətli məhsullar, ən yaxşı xidmətlər və ən ucuz qiymətlər üçün bizimlə qalacaqsınız.Biz sizə sərfəli və etibarlı alış veriş təcrübəsi təmin edə biləcəyimizə inanırıq. Hər zaman müştərilərimizin istəklərini əsas alırıq və onların məlumatlarını qoruyuruq.",
            freeShipping: "Pulsuz çatdırılma",
            freeShippingDesc: "10  AZN-dən yuxarı bütün sifarişlər",
            supportCustomer: "Dəstək Xidməti",
            supportCustomerDesc: "7/24 Xidmət",
            securePayments: "Təhlükəsiz Ödənişlər",
            securePaymentsDesc: "Təhlükəsizliyin qorunması",
            testimonial1: "Bu yaxınlarda bu mağazadan bir cüt ayaqqabı aldım. Sürətli xidmətə heyran oldum. Ayaqqabılar rahat və keyfiyyətlidir. Mən mütləq buradan yenidən alış-veriş edəcəyəm!",
            testimonial2: "Mağazada çoxlu məhsul seçimi var və mən axtardığımı tam olaraq tapa bildim. Qiymətlər münasib idi və müştəri xidməti əla idi. Bu mağazanı əla alış-veriş təcrübəsi axtaran hər kəsə tövsiyə edirəm.",
            testimonial3: "Uzun zamandır ki, bu mağazanın daimi müştərisiyəm və məhsulların müxtəlifliyi və keyfiyyəti məni həmişə heyran edir. Heyət həmişə mehriban və yardımseverdir və mən mümkün olan ən yaxşı alış-veriş təcrübəsini təmin etmək üçün onların xidmətini yüksək qiymətləndirirəm.",
            testimonial4: "Özəl bir gün üçün yeni paltara ehtiyacım var idi və bu mağazada tapdığım üçün çox sevindim. Aşağı qiymətə mükəmməl materialı tapa bildim. Mən mütləq tezliklə yenidən alış-verişə qayıdacağam!",
            sendUsMesssage: "Bizə mesaj göndərin",
            name: "Ad",
            email: "Email",
            surname: "Soyad",
            phone: "Telefon",
            submit: "Təsdiqlə",
            message: "Mesaj",
            address: "Ünvan",
            total: "Ümumi Məbləğ",
            goBasket: "Səbətə get",
            productName: "Məhsul adı",
            quantity: "Miqdarı",
            favorites: "FAVORİTLƏR",
            instagram: "Instagram",
            facebook: "Facebook",
            twitter:"Twitter",
            azn:"AZN"
        },
        ru: {
            home: "Главная",
            shop: "Магазин",
            about: "Подробности",
            faqs: "Вопрос и ответ",
            contact: "Контакт",
            learnMore: "Подробности",
            shopNow: "Начать покупки",
            forWoman: "Для женщин",
            forMan: "Для мужчин",
            bagShop: "Сумки",
            forKid: "Для детей",
            shoesShop: "Обувь",
            all: "Все",
            popular: "Популярный",
            brand: "Бренд",
            sale: "Скидка",
            instagramGallery: "Галерея Инстаграм",
            searchProducts: "Поиск продукта",
            categories: "Категории",
            kid: "Для детей",
            woman: "Для женщин",
            men: "Для мужчин",
            shoes: "Обувь",
            bag: "Сумки",
            color: "Цвет",
            filterByPrice: "Фильтровать по цене",
            size: "Размер",
            showing: "Показаны",
            results: "результатов",
            fromCheapToExpensive: "От дешевого к дорогому",
            fromExpensiveToCheap: "От дорогого к дешевому",
            a_z: "А - Я",
            z_a: "Я - A",
            availability: "Доступность",
            price: "Цена",
            inStock: "В наличии",
            notStock: "Нет в наличии",
            subcategory: "Подкатегория",
            category: "Категория",
            aboutTitle: "Все на расстоянии одного клика: легкие, быстрые и безопасные покупки!",
            aboutDesc: "Наш торговый магазин находится перед вами с современной и увлекательной платформой для наших клиентов, чтобы они могли совершать удобные и качественные покупки. У нас есть много разных категорий на выбор.Наш магазин - лучшая альтернатива для вашего шоппинга. Придя к нам, вы всегда останетесь с нами за качественные продукты, лучшие услуги и самые низкие цены Мы верим, что можем предоставить вам выгодный и надежный опыт покупок. Мы всегда берем пожелания наших клиентов за основу и защищаем их информацию",
            freeShipping: "Бесплатная доставка",
            freeShippingDesc: "Все заказы свыше 10  AZN",
            supportCustomer: "Сервис поддержки",
            supportCustomerDesc: "Круглосуточная служба",
            securePayments: "Безопасные платежи",
            securePaymentsDesc: "Защита безопасности",
            testimonial1: "Я недавно купил пару обуви в этом магазине. Я был впечатлен быстрым обслуживанием. Обувь удобная и качественная. Я определенно буду делать покупки здесь снова!`",
            testimonial2: "В магазине большой выбор товаров, и я смогла найти именно то, что искала. Цены были разумными, и обслуживание клиентов было превосходным. Рекомендую этот магазин всем, кто ищет приятных покупок.",
            testimonial3: "Я уже давно являюсь постоянным клиентом этого магазина и всегда впечатлен разнообразием и качеством продукции. Персонал всегда дружелюбный и услужливый, и я ценю их услуги, чтобы обеспечить наилучшие впечатления от покупок.",
            testimonial4: "Мне нужно было новое платье для особого дня, и я была так счастлива найти его в этом магазине. Я смог найти идеальный материал по низкой цене. Я обязательно вернусь за покупками в ближайшее время!",
            sendUsMesssage: "Отправьте нам сообщение",
            name: "Имя",
            email: "Электронная почта",
            surname: "Фамилия",
            phone: "Телефон",
            submit: "Подтверждать",
            message: "Сообщениеaj",
            address: "Адрес",
            total: "Всего к оплате",
            goBasket: "Перейти в корзину",
            productName: "Наименование товара",
            quantity: "Количество",
            favorites: "ИЗБРАННОЕ",
            instagram: "Инстаграм",
            facebook: "Фейсбук",
            twitter: "Твиттер",
            azn:"манат"
        }
    },
    aLang: localLang || "az",
    basket: localBasket ? JSON.parse(localBasket) : [],
    favorite: localFavorite ? JSON.parse(localFavorite) : []
}

export default function Reducer(state = initialState, action) {
    switch (action.type) {
        case "SET_PRODUCTS":
            return { ...state, products: action.payload };
        case "SET_CATEGORIES":
            return { ...state, categories: action.payload };
        case "SET_SUBCATEGORIES":
            return { ...state, subcategories: action.payload };
        case "SET_BASKET":
            return { ...state, basket: action.payload };
        case "SET_FAVORITE":
            return { ...state, favorite: action.payload };
        case "LANGUAGE":
            localStorage.setItem("lang", action.payload);
            return { ...state, aLang: action.payload };
        default:
            return state;
    }
}
